"""fix table users

Revision ID: a5515ce2dc71
Revises: 
Create Date: 2020-01-12 18:01:13.991909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5515ce2dc71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_index('id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('id', table_name='urls')
    op.drop_index('ix_urls_tag', table_name='urls')
    op.drop_index('ix_urls_url', table_name='urls')
    op.drop_index('sh_url', table_name='urls')
    op.drop_table('urls')
    op.drop_index('id', table_name='statistic')
    op.drop_table('statistic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('url', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('counter', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('chrome', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('firefox', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('yandex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('opera', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('other_br', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('android', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('windows', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('mac', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('linux', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('other_pl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date_use', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['url'], ['urls.id'], name='statistic_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'statistic', ['id'], unique=True)
    op.create_table('urls',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('sh_url', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tag', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='urls_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sh_url'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('sh_url', 'urls', ['sh_url'], unique=True)
    op.create_index('ix_urls_url', 'urls', ['url'], unique=False)
    op.create_index('ix_urls_tag', 'urls', ['tag'], unique=False)
    op.create_index('id', 'urls', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('id', 'users', ['id'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
